defaultPortal: production
portals:
  - name: production
    portalId: 26503447
    env: prod
    authType: personalaccesskey
    personalAccessKey: >-
      CiRldTEtZDNhMS1kZGEyLTQ4MTUtODI0MC04ZGYyNDczOWZkNGIQl9LRDBiN0vINKhkABeaRgmLAlGcZj_ooSyAQAdQH6Xi3egqrSgNldTE
    auth:
      tokenInfo:
        accessToken: >-
          CKb35eWnMxIjQlNQMl8kQEwrAhYACAkCARMcAQIBEAMKAQIDBxsDASQCeAEYl9LRDCCN0vINKO7pDDIUbI3_nAoQyDpbTT-jZW2YxRba5KM6ckJTUDJfJEBMKwIzABATBgAGAB0AAQABAAEAUQArABwAAQABAAEAAQAoAAEAAQABAAgAAQAGAAIAFAAEAA8AAQAIAAQAAQABAAEAAQABAAQAAQAFAAEAEgAJAAMAAQAxAAEADQABAEkAFwABAEIAVAEBAEIUTIdm71PTdpxoYyaGWrlB50j4PJpKA2V1MVIAWgBgAWiN0vINcAB4AA
        expiresAt: '2025-11-13T10:18:41.993Z'
    accountType: STANDARD
