defaultPortal: production
portals:
  - name: production
    portalId: 26503447
    env: prod
    authType: personalaccesskey
    personalAccessKey: >-
      CiRldTEtZDNhMS1kZGEyLTQ4MTUtODI0MC04ZGYyNDczOWZkNGIQl9LRDBiN0vINKhkABeaRgmLAlGcZj_ooSyAQAdQH6Xi3egqrSgNldTE
    accountType: STANDARD
