defaultPortal: production
portals:
  - name: production
    portalId: 26503447
    env: prod
    authType: personalaccesskey
    personalAccessKey: >-
      CiRldTEtZDNhMS1kZGEyLTQ4MTUtODI0MC04ZGYyNDczOWZkNGIQl9LRDBiN0vINKhkABeaRgmLAlGcZj_ooSyAQAdQH6Xi3egqrSgNldTE
    auth:
      tokenInfo:
        accessToken: >-
          CPXJyMenMxIjQlNQMl8kQEwrAhYACAkCARMcAQIBEAMKAQIDBxsDASQCeAEYl9LRDCCN0vINKO7pDDIUYyoC7AN7Ib1dCGme0dh67HCgFtU6ckJTUDJfJEBMKwIzABATBgAGAB0AAQABAAEAUQArABwAAQABAAEAAQAoAAEAAQABAAgAAQAGAAIAFAAEAA8AAQAIAAQAAQABAAEAAQABAAQAAQAFAAEAEgAJAAMAAQAxAAEADQABAEkAFwABAEIAVAEBAEIUkPOpXtkla4PGFKmXdbcPFQT8HM1KA2V1MVIAWgBgAWiN0vINcAB4AA
        expiresAt: '2025-11-12T16:42:06.490Z'
    accountType: STANDARD
